#!/usr/bin/env bash

set -euf -o pipefail

if [[ "${1:-"<no-arg>"}" != "--force" ]]; then
  echo """
  Desc:  Cancels CircleCI builds for previous commits on same branch
  Usage: cancel-previous-builds --force
  Examples...

      # Cancels builds for commits in same branch
      cancel-previous-builds --force

  """

  exit 255
fi

# circleci <curl-args...> <path>
function circleci() {
  curl --silent \
    -H "Content-Type: application/json" \
    -u "${CIRCLECI_TOKEN}:" \
    "${@:1:${#}-1}" \
    "https://circleci.com/api/v1.1${@:${#@}}"
}

USERNAME="${CIRCLE_PROJECT_USERNAME:-"<missing-username>"}"
REPO="${CIRCLE_PROJECT_REPONAME:-"<missing>"}"
PROJECT="${USERNAME}/${REPO}"
CIRCLE_BUILD_NUM="${CIRCLE_BUILD_NUM:-"<missing-circle-build-num>"}"
ENCODED_BRANCH="$(jq -Rr @uri <<< "${CIRCLE_BRANCH}")"  # urlsafe branchname

circleci --get \
  --data-urlencode "limit=100" \
  "/project/github/${PROJECT}/tree/${ENCODED_BRANCH}" \
  | jq "max_by(.build_num).vcs_revision as \$maxSha | map(select(.vcs_revision != \$maxSha))" \
  | jq "map(select(.lifecycle | test(\"running|queued|scheduled\")))" \
  | jq "map(select(.build_num != ${CIRCLE_BUILD_NUM}))" \
  | jq "map(.build_num) | .[]" -r \
  | while read -r BUILD_NUM; do
      STATUS=$( \
        circleci -s -o /dev/null -w '%{http_code}' -X POST \
          "/project/github/${PROJECT}/${BUILD_NUM}/cancel"
      )
      echo -e "Cancelled build ${BUILD_NUM}:\t${STATUS}"
    done

exit 0
